# build_axera_package.ps1 — AX650N package build on Windows/Docker Desktop.
#
# Mirrors build_sophon_package.ps1: the source tree is synced into a named
# ext4 volume (avoids 9P/drvfs build pathology), Linux .so symlinks are
# restored, then the AXERA builder image is built locally and compose runs
# scripts/build_axera_package.sh --chip ax650n.
#
# The AX650 SDK (msp/out) and the ARM GNU gcc-arm-9.2 toolchain stay in the
# WSL checkout (/opt/axera/...) and are bind-mounted into the build container
# through \\wsl$\<distro> paths — no disk-space-hungry copy into the repo.
#
# Prerequisites: Docker Desktop, WSL with /opt/axera/sdk/msp-out and
# /opt/axera/toolchain/gcc-arm-9.2 (see docs/development/axera-ax650-support-plan.md).
# Output:         build_output/ax650n/cosmo-*.tar.gz

$ErrorActionPreference = "Stop"

$VolumeName     = "cosmo-axera-source"
$ComposeFile    = "docker-compose.axera.yml"
$OverrideFile   = "docker-compose.axera.override.yml"
$Chip           = if ($args.Count -gt 0) { $args[0] } else { "ax650n" }
if ($Chip -ne "ax650n") {
    throw "Unsupported AXERA chip '$Chip'; expected ax650n"
}

$projectRoot = (Get-Location).Path
$dockerSrc   = $projectRoot.Replace('\', '/').Replace('C:', '/c').Replace('E:', '/e').Replace('D:', '/d')

function Write-Step([string]$message) {
    Write-Host ""
    Write-Host "=== $message ===" -ForegroundColor Cyan
}

function Invoke-Docker {
    param([Parameter(ValueFromRemainingArguments = $true)][string[]]$Args)
    $flat = ($Args | ForEach-Object { $_ }) -join " "
    cmd /c "docker $flat 2>&1"
    if ($LASTEXITCODE -ne 0) {
        throw "docker $flat failed (exit $LASTEXITCODE)"
    }
}

Write-Step "Step 1/6 - Checking Docker"
try { Invoke-Docker info | Out-Null } catch { Write-Error "Docker is not running. Start Docker Desktop, then re-run."; exit 1 }
Write-Host "Docker is ready"

Write-Step "Step 2/6 - Resolving WSL AX650 SDK + toolchain paths"
$distroLines = & wsl.exe -l -q 2>$null | Where-Object { $_ -and $_ -notmatch '^\s*$' }
$distro = ($distroLines | Select-Object -First 1).Trim()
if ([string]::IsNullOrWhiteSpace($distro)) {
    Write-Error "WSL has no distributions. Install WSL and stage the AX650 SDK first."
    exit 1
}
$sdkWsl = "/opt/axera/sdk/msp-out"
$tcWsl  = "/opt/axera/toolchain/gcc-arm-9.2"
$check  = & wsl.exe -d $distro bash -c "test -f $sdkWsl/include/ax_engine_api.h && test -x $tcWsl/bin/aarch64-none-linux-gnu-gcc && echo OK || echo MISSING"
if (($check | Select-Object -Last 1).Trim() -ne "OK") {
    Write-Error "WSL [$distro] is missing $sdkWsl or $tcWsl. Stage the AX650 SDK V3.10.2 msp/out and gcc-arm-9.2 there first."
    exit 1
}
$env:AXERA_SDK_WSL_ROOT       = "\\wsl$\$distro$($sdkWsl -replace '/', '\')"
$env:AXERA_TOOLCHAIN_WSL_ROOT = "\\wsl$\$distro$($tcWsl -replace '/', '\')"
Write-Host "  SDK:        $($env:AXERA_SDK_WSL_ROOT)"
Write-Host "  Toolchain:  $($env:AXERA_TOOLCHAIN_WSL_ROOT)"

Write-Step "Step 3/6 - Syncing source to Docker volume ($VolumeName)"
cmd /c "docker volume inspect $VolumeName >nul 2>nul"
if ($LASTEXITCODE -ne 0) {
    cmd /c "docker volume create $VolumeName >nul 2>nul"
    Write-Host "Created volume: $VolumeName"
}
Invoke-Docker run --rm `
    -v "${dockerSrc}:/src:ro" `
    -v "${VolumeName}:/workspace" `
    alpine sh /src/scripts/sync-source-volume.sh
Write-Host "Source sync complete"

Write-Step "Step 4/6 - Restoring Linux .so symlinks"
Invoke-Docker run --rm `
    -v "${VolumeName}:/workspace" `
    alpine sh /workspace/scripts/restore-symlinks.sh

Write-Step "Step 5/6 - Building AXERA builder image + cross-compiling $Chip"
# Generate a compose override that swaps the bind mount for the named volume,
# keeps ./build_output as a bind mount, re-declares the SDK/toolchain mounts
# (interpolated from $env:AXERA_*_WSL_ROOT), and preserves the ext4 build
# volume (CPack staging happens there, off the Windows drive).
@"
# Auto-generated by build_axera_package.ps1 - do not commit.
services:
  cosmo-axera-package:
    volumes:
      - ${VolumeName}:/workspace
      - ./build_output:/build_output
      - ${env:AXERA_SDK_WSL_ROOT}:/opt/axera/sdk/msp-out:ro
      - ${env:AXERA_TOOLCHAIN_WSL_ROOT}:/opt/axera/toolchain/gcc-arm-9.2:ro
      - cosmo-axera-build:/opt/axera/build
volumes:
  cosmo-axera-build:
  ${VolumeName}:
    external: true
"@ | Out-File -FilePath (Join-Path $projectRoot $OverrideFile) -Encoding utf8

Push-Location $projectRoot
try {
    cmd /c "docker compose -f $ComposeFile build 2>&1"
    if ($LASTEXITCODE -ne 0) {
        Write-Error "AXERA builder image build failed with exit code $LASTEXITCODE."
        exit $LASTEXITCODE
    }
    cmd /c "docker compose -f $ComposeFile -f $OverrideFile run --rm cosmo-axera-package --chip $Chip 2>&1"
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Docker build failed with exit code $LASTEXITCODE."
        exit $LASTEXITCODE
    }
} finally {
    Pop-Location
    Remove-Item (Join-Path $projectRoot $OverrideFile) -Force -ErrorAction SilentlyContinue
}

Write-Step "Step 6/6 - Build output"
$outputDir = Join-Path $projectRoot "build_output\$Chip"
if (Test-Path $outputDir) {
    $packages = Get-ChildItem $outputDir -Filter "*.tar.gz"
    if ($packages) {
        foreach ($pkg in $packages) {
            Write-Host "  $($pkg.Name)  ($('{0:N0}' -f $pkg.Length) bytes)" -ForegroundColor Green
        }
    } else {
        Write-Warning "No .tar.gz found in build_output/$Chip/"
    }
} else {
    Write-Warning "build_output/$Chip/ directory not found"
}

Write-Host ""
Write-Host "=== AX650N build completed ===" -ForegroundColor Green
